// Generated by gencpp from file aam_common_msgs/ConeDetections.msg
// DO NOT EDIT!


#ifndef AAM_COMMON_MSGS_MESSAGE_CONEDETECTIONS_H
#define AAM_COMMON_MSGS_MESSAGE_CONEDETECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <aam_common_msgs/Cone.h>

namespace aam_common_msgs
{
template <class ContainerAllocator>
struct ConeDetections_
{
  typedef ConeDetections_<ContainerAllocator> Type;

  ConeDetections_()
    : header()
    , cone_detections()  {
    }
  ConeDetections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cone_detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::aam_common_msgs::Cone_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aam_common_msgs::Cone_<ContainerAllocator> >> _cone_detections_type;
  _cone_detections_type cone_detections;





  typedef boost::shared_ptr< ::aam_common_msgs::ConeDetections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aam_common_msgs::ConeDetections_<ContainerAllocator> const> ConstPtr;

}; // struct ConeDetections_

typedef ::aam_common_msgs::ConeDetections_<std::allocator<void> > ConeDetections;

typedef boost::shared_ptr< ::aam_common_msgs::ConeDetections > ConeDetectionsPtr;
typedef boost::shared_ptr< ::aam_common_msgs::ConeDetections const> ConeDetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aam_common_msgs::ConeDetections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aam_common_msgs::ConeDetections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aam_common_msgs::ConeDetections_<ContainerAllocator1> & lhs, const ::aam_common_msgs::ConeDetections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cone_detections == rhs.cone_detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aam_common_msgs::ConeDetections_<ContainerAllocator1> & lhs, const ::aam_common_msgs::ConeDetections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aam_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aam_common_msgs::ConeDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aam_common_msgs::ConeDetections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aam_common_msgs::ConeDetections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aam_common_msgs::ConeDetections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aam_common_msgs::ConeDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aam_common_msgs::ConeDetections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aam_common_msgs::ConeDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98c8c85adf89b9e9d5d8cd2b615e2a7e";
  }

  static const char* value(const ::aam_common_msgs::ConeDetections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98c8c85adf89b9e9ULL;
  static const uint64_t static_value2 = 0xd5d8cd2b615e2a7eULL;
};

template<class ContainerAllocator>
struct DataType< ::aam_common_msgs::ConeDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aam_common_msgs/ConeDetections";
  }

  static const char* value(const ::aam_common_msgs::ConeDetections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aam_common_msgs::ConeDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"aam_common_msgs/Cone[] cone_detections\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: aam_common_msgs/Cone\n"
"geometry_msgs/Point position   # coordinate of cone in [x, y]\n"
"std_msgs/String color   # color of cone, 'b' = blue, 'y' = yellow, 'so' = orange , 'bo' = orange\n"
"float64 ratioX\n"
"float64 ratioY\n"
"float64 pcX\n"
"float64 pcY\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::aam_common_msgs::ConeDetections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aam_common_msgs::ConeDetections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cone_detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeDetections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aam_common_msgs::ConeDetections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aam_common_msgs::ConeDetections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cone_detections[]" << std::endl;
    for (size_t i = 0; i < v.cone_detections.size(); ++i)
    {
      s << indent << "  cone_detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aam_common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.cone_detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AAM_COMMON_MSGS_MESSAGE_CONEDETECTIONS_H
