// Generated by gencpp from file aam_common_msgs/Map.msg
// DO NOT EDIT!


#ifndef AAM_COMMON_MSGS_MESSAGE_MAP_H
#define AAM_COMMON_MSGS_MESSAGE_MAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <aam_common_msgs/Cone.h>
#include <aam_common_msgs/Cone.h>
#include <aam_common_msgs/Cone.h>
#include <aam_common_msgs/Cone.h>

namespace aam_common_msgs
{
template <class ContainerAllocator>
struct Map_
{
  typedef Map_<ContainerAllocator> Type;

  Map_()
    : header()
    , cone_yellow()
    , cone_blue()
    , orange()
    , cone_unknow()  {
    }
  Map_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cone_yellow(_alloc)
    , cone_blue(_alloc)
    , orange(_alloc)
    , cone_unknow(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::aam_common_msgs::Cone_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aam_common_msgs::Cone_<ContainerAllocator> >> _cone_yellow_type;
  _cone_yellow_type cone_yellow;

   typedef std::vector< ::aam_common_msgs::Cone_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aam_common_msgs::Cone_<ContainerAllocator> >> _cone_blue_type;
  _cone_blue_type cone_blue;

   typedef std::vector< ::aam_common_msgs::Cone_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aam_common_msgs::Cone_<ContainerAllocator> >> _orange_type;
  _orange_type orange;

   typedef std::vector< ::aam_common_msgs::Cone_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aam_common_msgs::Cone_<ContainerAllocator> >> _cone_unknow_type;
  _cone_unknow_type cone_unknow;





  typedef boost::shared_ptr< ::aam_common_msgs::Map_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aam_common_msgs::Map_<ContainerAllocator> const> ConstPtr;

}; // struct Map_

typedef ::aam_common_msgs::Map_<std::allocator<void> > Map;

typedef boost::shared_ptr< ::aam_common_msgs::Map > MapPtr;
typedef boost::shared_ptr< ::aam_common_msgs::Map const> MapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aam_common_msgs::Map_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aam_common_msgs::Map_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aam_common_msgs::Map_<ContainerAllocator1> & lhs, const ::aam_common_msgs::Map_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cone_yellow == rhs.cone_yellow &&
    lhs.cone_blue == rhs.cone_blue &&
    lhs.orange == rhs.orange &&
    lhs.cone_unknow == rhs.cone_unknow;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aam_common_msgs::Map_<ContainerAllocator1> & lhs, const ::aam_common_msgs::Map_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aam_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aam_common_msgs::Map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aam_common_msgs::Map_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aam_common_msgs::Map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aam_common_msgs::Map_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aam_common_msgs::Map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aam_common_msgs::Map_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aam_common_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d926454e54ff8605a5b5a6710745bd29";
  }

  static const char* value(const ::aam_common_msgs::Map_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd926454e54ff8605ULL;
  static const uint64_t static_value2 = 0xa5b5a6710745bd29ULL;
};

template<class ContainerAllocator>
struct DataType< ::aam_common_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aam_common_msgs/Map";
  }

  static const char* value(const ::aam_common_msgs::Map_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aam_common_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"aam_common_msgs/Cone[] cone_yellow\n"
"aam_common_msgs/Cone[] cone_blue\n"
"aam_common_msgs/Cone[] orange\n"
"aam_common_msgs/Cone[] cone_unknow\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: aam_common_msgs/Cone\n"
"geometry_msgs/Point position   # coordinate of cone in [x, y]\n"
"std_msgs/String color   # color of cone, 'b' = blue, 'y' = yellow, 'so' = orange , 'bo' = orange\n"
"float64 ratioX\n"
"float64 ratioY\n"
"float64 pcX\n"
"float64 pcY\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::aam_common_msgs::Map_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aam_common_msgs::Map_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cone_yellow);
      stream.next(m.cone_blue);
      stream.next(m.orange);
      stream.next(m.cone_unknow);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Map_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aam_common_msgs::Map_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aam_common_msgs::Map_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cone_yellow[]" << std::endl;
    for (size_t i = 0; i < v.cone_yellow.size(); ++i)
    {
      s << indent << "  cone_yellow[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aam_common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.cone_yellow[i]);
    }
    s << indent << "cone_blue[]" << std::endl;
    for (size_t i = 0; i < v.cone_blue.size(); ++i)
    {
      s << indent << "  cone_blue[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aam_common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.cone_blue[i]);
    }
    s << indent << "orange[]" << std::endl;
    for (size_t i = 0; i < v.orange.size(); ++i)
    {
      s << indent << "  orange[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aam_common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.orange[i]);
    }
    s << indent << "cone_unknow[]" << std::endl;
    for (size_t i = 0; i < v.cone_unknow.size(); ++i)
    {
      s << indent << "  cone_unknow[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aam_common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.cone_unknow[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AAM_COMMON_MSGS_MESSAGE_MAP_H
