// Generated by gencpp from file ma_rrt_path_plan/Map.msg
// DO NOT EDIT!


#ifndef MA_RRT_PATH_PLAN_MESSAGE_MAP_H
#define MA_RRT_PATH_PLAN_MESSAGE_MAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace ma_rrt_path_plan
{
template <class ContainerAllocator>
struct Map_
{
  typedef Map_<ContainerAllocator> Type;

  Map_()
    : header()
    , cones()  {
    }
  Map_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cones(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _cones_type;
  _cones_type cones;





  typedef boost::shared_ptr< ::ma_rrt_path_plan::Map_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ma_rrt_path_plan::Map_<ContainerAllocator> const> ConstPtr;

}; // struct Map_

typedef ::ma_rrt_path_plan::Map_<std::allocator<void> > Map;

typedef boost::shared_ptr< ::ma_rrt_path_plan::Map > MapPtr;
typedef boost::shared_ptr< ::ma_rrt_path_plan::Map const> MapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ma_rrt_path_plan::Map_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ma_rrt_path_plan::Map_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ma_rrt_path_plan::Map_<ContainerAllocator1> & lhs, const ::ma_rrt_path_plan::Map_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cones == rhs.cones;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ma_rrt_path_plan::Map_<ContainerAllocator1> & lhs, const ::ma_rrt_path_plan::Map_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ma_rrt_path_plan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ma_rrt_path_plan::Map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ma_rrt_path_plan::Map_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ma_rrt_path_plan::Map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ma_rrt_path_plan::Map_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ma_rrt_path_plan::Map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ma_rrt_path_plan::Map_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ma_rrt_path_plan::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a76cc715406ffc6cf9539510030fd7bf";
  }

  static const char* value(const ::ma_rrt_path_plan::Map_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa76cc715406ffc6cULL;
  static const uint64_t static_value2 = 0xf9539510030fd7bfULL;
};

template<class ContainerAllocator>
struct DataType< ::ma_rrt_path_plan::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ma_rrt_path_plan/Map";
  }

  static const char* value(const ::ma_rrt_path_plan::Map_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ma_rrt_path_plan::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point[] cones\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ma_rrt_path_plan::Map_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ma_rrt_path_plan::Map_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cones);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Map_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ma_rrt_path_plan::Map_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ma_rrt_path_plan::Map_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cones[]" << std::endl;
    for (size_t i = 0; i < v.cones.size(); ++i)
    {
      s << indent << "  cones[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.cones[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MA_RRT_PATH_PLAN_MESSAGE_MAP_H
