// Generated by gencpp from file ma_rrt_path_plan/WaypointsArray.msg
// DO NOT EDIT!


#ifndef MA_RRT_PATH_PLAN_MESSAGE_WAYPOINTSARRAY_H
#define MA_RRT_PATH_PLAN_MESSAGE_WAYPOINTSARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ma_rrt_path_plan/Waypoint.h>

namespace ma_rrt_path_plan
{
template <class ContainerAllocator>
struct WaypointsArray_
{
  typedef WaypointsArray_<ContainerAllocator> Type;

  WaypointsArray_()
    : header()
    , preliminaryLoopClosure(false)
    , loopClosure(false)
    , waypoints()  {
    }
  WaypointsArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , preliminaryLoopClosure(false)
    , loopClosure(false)
    , waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _preliminaryLoopClosure_type;
  _preliminaryLoopClosure_type preliminaryLoopClosure;

   typedef uint8_t _loopClosure_type;
  _loopClosure_type loopClosure;

   typedef std::vector< ::ma_rrt_path_plan::Waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ma_rrt_path_plan::Waypoint_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointsArray_

typedef ::ma_rrt_path_plan::WaypointsArray_<std::allocator<void> > WaypointsArray;

typedef boost::shared_ptr< ::ma_rrt_path_plan::WaypointsArray > WaypointsArrayPtr;
typedef boost::shared_ptr< ::ma_rrt_path_plan::WaypointsArray const> WaypointsArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator1> & lhs, const ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.preliminaryLoopClosure == rhs.preliminaryLoopClosure &&
    lhs.loopClosure == rhs.loopClosure &&
    lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator1> & lhs, const ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ma_rrt_path_plan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f11df5cc21094a3f66524c757aa5cb93";
  }

  static const char* value(const ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf11df5cc21094a3fULL;
  static const uint64_t static_value2 = 0x66524c757aa5cb93ULL;
};

template<class ContainerAllocator>
struct DataType< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ma_rrt_path_plan/WaypointsArray";
  }

  static const char* value(const ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool preliminaryLoopClosure\n"
"bool loopClosure\n"
"Waypoint[] waypoints\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ma_rrt_path_plan/Waypoint\n"
"int32 id\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.preliminaryLoopClosure);
      stream.next(m.loopClosure);
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointsArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ma_rrt_path_plan::WaypointsArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "preliminaryLoopClosure: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.preliminaryLoopClosure);
    s << indent << "loopClosure: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.loopClosure);
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ma_rrt_path_plan::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MA_RRT_PATH_PLAN_MESSAGE_WAYPOINTSARRAY_H
